First_request
embedded-dev-research/itlab_2022 pull request #1
Opened 2023-04-04 21:12 UTC by IzmaylovI

2023-04-05 15:02 UTC, aobolensk commented on CMakeLists.txt
> +set(CMAKE_C_COMPILER "C:/MinGW/bin/gcc.exe")
This solution is not universal, at least do not override C/CXX compiler if it is already found

2023-04-05 15:02 UTC, aobolensk commented on headers/Color.hpp
> +enum mode { rgb, bgr };
It is not the mode in fact, it could be called "layout"

2023-04-05 15:02 UTC, aobolensk commented on headers/Function.hpp
> +/*
Do we need this comment?

2023-04-05 15:02 UTC, aobolensk commented on headers/Structer.hpp
> +    Mtrx(int height_m = 0, int width_m = 0, ValType element = 0);
Why do we have default width/height set to 0?

2023-04-05 19:53 UTC, IzmaylovI commented
Fixed the code:
1) removed the override C/CXX compiler.
2) renamed mode to layout
3) removed the commentaries in the file Function.hpp. For matrices of elements of the base type, everything will work. For pixel matrices, one more function needs to be implemented
4) removed the default value of 0 in width/height because there is no need for this

2023-04-11 12:09 UTC, allnes requested changes

2023-04-11 12:09 UTC, allnes commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
please set OpenMP's flags when `OpenMP_FOUND` is true

2023-04-11 12:09 UTC, allnes commented on README.md
> +### Module 1.
Please name the modules according to their purpose

2023-04-11 12:09 UTC, allnes commented on headers/Structer.hpp
> +class Mtrx {
I think this class should be made purely abstract. 
@aobolensk how do you think?

2023-04-12 13:23 UTC, allnes commented
@IzmaylovI please correct commit changes, old changes is lost

2023-04-12 14:06 UTC, IzmaylovI commented
Corrected the commit. Is there anything else that needs to be corrected?

2023-04-12 15:47 UTC, allnes approved these changes

2023-04-14 03:15 UTC, aobolensk commented
Please, update the title and provide description. I think it is better to squash this pull request and we need to preserve quality information in main branch commit. Other things LGTM

2023-04-14 03:15 UTC, aobolensk commented
@allnes please, use squash strategy when we will be merging this PR

2023-04-14 15:03 UTC, IzmaylovI commented
> Please, update the title and provide description. I think it is better to squash this pull request and we need to preserve quality information in main branch commit. Other things LGTM


where do we need to change the description?

2023-04-14 15:04 UTC, aobolensk commented
> > Please, update the title and provide description. I think it is better to squash this pull request and we need to preserve quality information in main branch commit. Other things LGTM
> 
> 
> where do we need to change the description?

Description of this pull request

2023-04-14 15:54 UTC, IzmaylovI commented
1) Removed extra lines in CMakeLists.txt
2) Wrote non-template matrix multiplication functions using intrinsics
3) Тame the modules according to their purpose in Readme.md
4) Set OpenMP's flags when "OpenMP_FOUND" is true  in CMakeLists.txt
5) Deleted unnecessary file - BMP.cpp 
6) Removed unnecessary comments in files

2023-04-16 04:17 UTC, aobolensk approved these changes

2023-04-16 04:18 UTC, merged