renamed the data generation file + added generators (integer, double, char)
embedded-dev-research/itlab_2022 pull request #4
Opened 2023-04-17 21:40 UTC by Kuznetsov-Artyom

2023-04-18 15:42 UTC, allnes commented on CMakeLists.txt
> +add_executable(computer_vision main.cpp ./headers/Structer.hpp ./headers/genRandData.hpp ./headers/Color.hpp ./headers/BMP.hpp)
please use universal find ([docs](https://cmake.org/cmake/help/latest/command/find_file.html))

2023-04-18 15:45 UTC, allnes commented on headers/genRandData.hpp
> +	class DoubleGenerator
why do you use template and create few generators. If you use template please use one generator for all data type

2023-04-24 11:37 UTC, aobolensk requested changes

2023-04-24 11:37 UTC, aobolensk commented on headers/genRandData.hpp
> +	inline void DoubleGenerator<T>::checkRange(const T& min, const T& max)
Usually check* functions are supposed to return bool

2023-04-24 11:37 UTC, aobolensk commented on headers/genRandData.hpp
> +#include <climits>
Why do we need this include?

2023-04-24 14:47 UTC, Kuznetsov-Artyom commented on headers/genRandData.hpp
> +#include <climits>
> Why do we need this include?

std::uniform_int_distribution and uniform_real_distribution are located in the header file <random>

2023-04-25 09:11 UTC, Kuznetsov-Artyom commented on headers/genRandData.hpp
> +	class DoubleGenerator
> why do you use template and create few generators. If you use template please use one generator for all data type

I fixed it, please check out the new commit

2023-04-25 09:13 UTC, Kuznetsov-Artyom commented on headers/genRandData.hpp
> +	inline void DoubleGenerator<T>::checkRange(const T& min, const T& max)
> Usually check* functions are supposed to return bool

I agree. Please check out the new commit

2023-04-25 18:40 UTC, aobolensk commented on headers/genRandData.hpp
> +#include <climits>
The question is actually about climits

2023-04-25 20:54 UTC, Kuznetsov-Artyom commented on headers/genRandData.hpp
> +#include <climits>
I used macros for boundary ranges. It may be worth removing this header. Since, if necessary, the user himself will connect it from outside

2023-04-28 14:44 UTC, allnes commented
@Kuznetsov-Artyom please update master and resolve conflicts

2023-05-05 14:38 UTC, Kuznetsov-Artyom commented
> @Kuznetsov-Artyom please update master and resolve conflicts

I don't understand the reason for the conflicts, I mode 3  commits on Tuesday, but I had to roll back.

2023-05-12 20:05 UTC, aobolensk commented on headers/gen_rand_data.hpp
> +#define _GEN_RAND_DATA_END }
Why do we need defines here?

2023-05-12 20:14 UTC, Kuznetsov-Artyom commented on headers/gen_rand_data.hpp
> +#define _GEN_RAND_DATA_END }
> Why do we need defines here?

Initially, I did not know how to get around the problem with formatting the style, CI required everything to be demolished to the left side.

2023-05-12 20:21 UTC, Kuznetsov-Artyom commented on headers/gen_rand_data.hpp
> +#define _GEN_RAND_DATA_END }
> Why do we need defines here?

Fixed everything. Please take a look.

2023-05-12 20:30 UTC, aobolensk approved these changes
LGTM
@allnes please, take a look

2023-05-13 20:38 UTC, allnes approved these changes

2023-05-13 20:38 UTC, merged

2023-05-14 07:18 UTC, aobolensk commented
@allnes I guess, it was better to squash commits here as well