dividing_into_modules-creating_folders
embedded-dev-research/itlab_2022 pull request #5
Opened 2023-04-21 14:41 UTC by IzmaylovI

1) Created new folders so that there is a division in accordance with the descriptions presented in the file Readme.md
2) A timer class has been created that will count the time for benchmarks
3) Fixed Readme.md

2023-04-23 07:42 UTC, aobolensk requested changes

2023-04-23 07:42 UTC, aobolensk commented on benchmarks/sources/timer.cpp
> +    if (strt == false)
```suggestion
    if (!strt)
```

2023-04-23 07:42 UTC, aobolensk commented on benchmarks/headers/timer.hpp
> +    double duration_ms();
1. Let's use RAII C++ paradigm to start/stop timer
2. We need to add usage example here maybe

2023-04-23 07:42 UTC, aobolensk commented on CMakeLists.txt
> +set(SRC1 benchmarks/sources/timer.cpp)
```suggestion
set(BENCHMARK_HDR benchmarks/headers/timer.hpp)
set(BENCHMARK_SRC benchmarks/sources/timer.cpp)
```

2023-04-23 07:42 UTC, aobolensk commented on CMakeLists.txt
> +set(SRC algorithms/sources/function.cpp)
```suggestion
set(ALGORITHMS_HDR algorithms/headers/function.hpp)
set(ALGORITHMS_SRC algorithms/sources/function.cpp)
```

2023-04-23 07:42 UTC, aobolensk commented on CMakeLists.txt
> +include_directories(./generating_data/headers ./algorithms/headers ./tests/headers ./benchmarks/headers)
It is better to do 4 calls of `include_directories` instead of adding 4 directories into 1 call

2023-04-23 10:17 UTC, IzmaylovI commented
The following changes have been made:
1. added a constructor and destructor to make the class match the RAII
2. some examples of using the Timer are written in Timer.hpp
3. written  4 calls of `include_directories` in CMakeLists.txt

2023-04-25 18:40 UTC, aobolensk requested changes

2023-04-25 18:40 UTC, aobolensk commented on benchmarks/headers/timer.hpp
> +// OUTPUT warning: Warning!!! The timer did not stop
I am not sure that comment is a good idea here

2023-04-25 18:40 UTC, aobolensk commented on benchmarks/headers/timer.hpp
> +    Timer();                // сonstructor: initializes the timer duration to zero microseconds
Timer is still actually not RAII

2023-04-25 18:45 UTC, IzmaylovI commented on benchmarks/headers/timer.hpp
> +    Timer();                // сonstructor: initializes the timer duration to zero microseconds
Is it because the capture of the resource "time" does not occur in the constructor?

2023-04-25 18:47 UTC, IzmaylovI commented on benchmarks/headers/timer.hpp
> +// OUTPUT warning: Warning!!! The timer did not stop
Where can I add an usage example?

2023-04-25 18:48 UTC, aobolensk commented on benchmarks/headers/timer.hpp
> +    Timer();                // сonstructor: initializes the timer duration to zero microseconds
RAII here approximately means something like that:
```
Timer() {start();}
~Timer() {stop(); std::cout << "time " << ...; }
```

2023-04-25 18:54 UTC, IzmaylovI commented on benchmarks/headers/timer.hpp
> +    Timer();                // сonstructor: initializes the timer duration to zero microseconds
Would it be possible in this case to use the Timer class to measure time in the benchmark class? If at the same time we want to save the duration of the Timer in some other variable.

2023-04-25 19:04 UTC, IzmaylovI commented on benchmarks/headers/timer.hpp
> +    Timer();                // сonstructor: initializes the timer duration to zero microseconds
`class Benchmark{
private: 
    double time_exec;                // execution time of the function under test
    std::function<void()> func;  // function under benchmark
public:
     ...
    void run(){
        double tmp_time = 0;
        Timer t;
        for(int i = 0; i < 10; i++){
            t.start();
            func();
            t.stop();
            tmp_time = t.duration_s();
        }
        time_exec = tmp_time/10;
}``class Benchmark{
private: 
    double time_exec;                // execution time of the function under test
    std::function<void()> func;  // function under benchmark
public:
     ...
    void run(){
        double tmp_time = 0;
        Timer t;
        for(int i = 0; i < 10; i++){
            t.start();
            func();
            t.stop();
            tmp_time = t.duration_s();
        }
        time_exec = tmp_time/10;
}`

2023-04-28 14:45 UTC, allnes commented
@IzmaylovI please update master and resolve conflicts

2023-05-04 11:31 UTC, IzmaylovI commented
Tell me, please, for what reason do conflicts arise?

2023-05-04 11:39 UTC, closed without merging